/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.jvmc.projetocampominado.gui.menu;

import edu.jvmc.projetocampominado.Principal;
import edu.jvmc.projetocampominado.gui.jogo.PainelJogo;

/**
 *
 * @author Jarvis 3.0
 */
public class MenuInicial extends javax.swing.JPanel {

    /**
     * Creates new form MenuInicial
     */
    Principal framePai;
    public MenuInicial(Principal framePai) {
        initComponents();
        this.framePai = framePai;
        this.setSize(800,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btJogar = new javax.swing.JButton();
        btPontuacao = new javax.swing.JButton();

        setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel1.setText("CAMPO MINADO");
        add(jLabel1);
        jLabel1.setBounds(220, 100, 390, 70);

        btJogar.setText("JOGAR");
        btJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJogarActionPerformed(evt);
            }
        });
        add(btJogar);
        btJogar.setBounds(300, 270, 180, 23);

        btPontuacao.setText("PONTUAÇÕES");
        add(btPontuacao);
        btPontuacao.setBounds(300, 330, 180, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJogarActionPerformed
        this.framePai.trocarPainel(new PainelJogo());
        
    }//GEN-LAST:event_btJogarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btJogar;
    private javax.swing.JButton btPontuacao;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
